// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejbkbhocbsagahjeqcba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqYmtiaG9jYnNhZ2FoamVxY2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNjE1MjEsImV4cCI6MjA0OTczNzUyMX0.-62Dg0vtoKRap-xU_R5QQpLaEwtJ2AtJS7hOhwpdPnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);